language: python
sudo: false

jdk:
- openjdk7

install:
- pip install --upgrade pip
- pip install --upgrade tox

env:
- TEST_DIR=java TEST_CMD='mvn test'
- TEST_DIR=python TEST_CMD='tox -e py27'

script:
- cd $TEST_DIR && $TEST_CMD